version: '3.8'
services:
  api:
    image: ghcr.io/ghoshritesh12/aniwatch:v2.9.0
    container_name: aniwatch-api
    restart: unless-stopped
    ports:
      - "4000:4000"

  bot:
    build: .
    container_name: hianime-bot
    depends_on:
      - api
    restart: on-failure
    env_file: .env

    # Persist the Telethon session file so you only import once
    volumes:
      - ./session:/app/session
